version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: novels_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: novels
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: novels_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  meilisearch:
    image: getmeili/meilisearch:v1.9
    container_name: novels_meili
    restart: unless-stopped
    environment:
      MEILI_NO_ANALYTICS: "true"
    ports:
      - "7700:7700"

  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    container_name: novels_minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

volumes:
  pgdata: {}
  miniodata: {}
